export const FETCHING_DATA_REQUEST="FETCHING_DATA_REQUEST"
export const FETCHING_DATA_SUCCESS="FETCHING_DATA_SUCCESS"
export const FETCHING_DATA_FAIL="FETCHING_DATA_FAIL"

export const FILTERING_DATA_REQUEST="FILTERING_DATA_REQUEST"
export const FILTERING_DATA_SUCCESS="FILTERING_DATA_SUCCESS"
export const FILTERING_DATA_FAIL="FILTERING_DATA_FAIL"